[package]
name = "async_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-task = { version = "0.3.20", default-features = false, features = ["alloc"] }
spin = "0"